import { ViewTransition, type SVGProps } from "react";
import Link from "next/link";
import { t } from "@/i18n/en";
import { cn } from "@/lib/utils";
import { wordmark } from "@/assets/brand/wordmark";

/**
 * Shared view-transition name so the mark persists (morphs) across route
 * changes, e.g. site header -> admin sign-in. Next 16 App Router runs React's
 * <ViewTransition> with no config flag (there is no experimental.viewTransition).
 */
export const WORDMARK_VT_NAME = "gwallaga-wordmark";

export interface WordmarkGlyphsProps extends Omit<SVGProps<SVGSVGElement>, "viewBox" | "children"> {
  /** "fill" for the static mark, "stroke" for the draw-in variant. */
  variant?: "fill" | "stroke";
}

/**
 * The Arabic wordmark as inline SVG outlines (generated by `pnpm brand`), one
 * <path class="g" data-i> per glyph so motion can address glyphs. Decorative:
 * callers label the surrounding link or region.
 */
export function WordmarkGlyphs({ variant = "fill", className, ...props }: WordmarkGlyphsProps) {
  const paint =
    variant === "fill"
      ? { fill: "currentColor" }
      : {
          fill: "none",
          stroke: "currentColor",
          strokeWidth: wordmark.strokeWidth,
          strokeLinejoin: "round" as const,
          strokeLinecap: "round" as const,
        };
  return (
    <svg
      viewBox={wordmark.viewBox}
      aria-hidden
      focusable="false"
      className={cn("block h-auto overflow-visible", className)}
      {...paint}
      {...props}
    >
      {wordmark.paths.map((d, i) => (
        <path key={i} className="g" data-i={i} d={d} />
      ))}
    </svg>
  );
}

/**
 * Arabic mark (glyph outlines) + "Gwallaga" in Fraunces. Inside the header the
 * compact state (scrolled past the hero) is driven by `data-compact` on an
 * ancestor with the `group/header` class: the Arabic shrinks, the Latin fades.
 * Transform/opacity only. `compact` (prop) drops the Arabic for tight spaces.
 */
export function Wordmark({ className, compact = false }: { className?: string; compact?: boolean }) {
  return (
    <ViewTransition name={WORDMARK_VT_NAME}>
    <Link
      href="/"
      aria-label={t.a11y.home}
      data-wordmark
      className={cn("group/wm relative inline-flex items-center gap-2.5 leading-none sm:gap-3.5", className)}
    >
      {compact ? null : (
        <WordmarkGlyphs
          data-wordmark-mark
          className={cn(
            "w-[7.25rem] shrink-0 origin-left sm:w-[8.5rem]",
            "transition-transform duration-[900ms] ease-(--ease-spring-physics) motion-reduce:transition-none",
            "group-data-[compact=true]/header:scale-[0.84]",
          )}
        />
      )}
      {compact ? null : (
        <span
          aria-hidden
          className={cn(
            "hidden h-6 w-px origin-center bg-line-strong sm:block",
            "transition-[transform,opacity] duration-700 ease-[var(--ease-spring)] motion-reduce:transition-none",
            "group-data-[compact=true]/header:-translate-x-5 group-data-[compact=true]/header:scale-y-0 group-data-[compact=true]/header:opacity-0",
          )}
        />
      )}
      <span
        data-wordmark-latin
        className={cn(
          "font-display text-[1.5rem] tracking-[-0.03em] [font-variation-settings:'SOFT'_100,'opsz'_72]",
          "transition-[transform,opacity] duration-700 ease-(--ease-spring-physics) motion-reduce:transition-none",
          "group-data-[compact=true]/header:-translate-x-5 group-data-[compact=true]/header:opacity-0",
        )}
      >
        {t.site.shortName}
      </span>
    </Link>
    </ViewTransition>
  );
}
